# Generated by Django 5.1.4 on 2025-05-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_with_northern_valley', '0002_traveltip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveltip',
            name='date',
        ),
        migrations.AddField(
            model_name='traveltip',
            name='tenure',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='traveltip',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
