# Generated by Django 5.1.4 on 2025-05-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_with_northern_valley', '0004_itineraryday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryday',
            name='image',
        ),
        migrations.CreateModel(
            name='ItineraryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='itinerary_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('itinerary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel_with_northern_valley.itineraryday')),
            ],
        ),
    ]
