# Generated by Django 5.1.4 on 2025-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_with_northern_valley', '0005_remove_itineraryday_image_itineraryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltip',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
