# Generated by Django 5.1.4 on 2025-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_with_northern_valley', '0006_traveltip_firebase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltip',
            name='tenure',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
